#!/usr/bin/with-contenv bash

# shellcheck shell=bash

set -e

qbt settings set url "http://localhost:$WEBUI_PORT"

while true; do

    while [ "$(findmnt -f -o AVAIL -b -n -T /downloads)" -lt "${MIN_FREE}" ]; do
        
        oldest_download="$(qbt torrent list -f completed -s CompletionOn -l 1 -F json | jq -r '.[0].hash')"
        if [ "$oldest_download" = "null" ]; then
            echo "WARNING: There are no torrents to delete despite the disk being low on space."
            break
        fi

        qbt torrent delete -f "$oldest_download"
    done

    sleep $(( $(date -d "tomorrow ${DELETE_TIME}" +%s) - $(date +%s) ))
done
