#!/usr/bin/with-contenv bash

# shellcheck shell=bash

while [ ! -f /var/run/vpn-up ]; do
    echo "Waiting for VPN before running qbittorrent..."
    sleep 1
done

WEBUI_PORT=${WEBUI_PORT:-8080}
exec s6-setuidgid abc /usr/bin/qbittorrent-nox --webui-port="${WEBUI_PORT}"
