#!/usr/bin/with-contenv bash

# shellcheck shell=bash

set -e

sleep 3

TEMP_DIR="$(mktemp -d)"

if [ ! -f "${OPENVPN_CONFIG_FILE}" ] ; then
    echo "No OpenVPN config. Exiting."
    exit 1
fi

# Add ovpn user/pass
if [ -n "${OPENVPN_USERNAME}" ]; then
    echo "$OPENVPN_USERNAME" >"${TEMP_DIR}/openvpn-credentials.txt"
    echo "$OPENVPN_PASSWORD" >>"${TEMP_DIR}/openvpn-credentials.txt"
    chmod 600 "${TEMP_DIR}/openvpn-credentials.txt"

    grep -v "auth-user-pass" <"${OPENVPN_CONFIG_FILE}" >"${TEMP_DIR}/config.ovpn"
    echo "auth-user-pass ${TEMP_DIR}/openvpn-credentials.txt" >>"${TEMP_DIR}/config.ovpn"
fi

if [ ! -f "${TEMP_DIR}/config.ovpn" ]; then
    cp "${OPENVPN_CONFIG_FILE}" "${TEMP_DIR}/config.ovpn"
fi

exec openvpn \
    --config "${TEMP_DIR}/config.ovpn" \
    --connect-retry-max 1 \
    --resolv-retry 1 \
    --script-security 2 \
    --up /usr/local/bin/up \
    --down /usr/local/bin/down
